version: '3'

services:
    mysql:
        container_name: csv-import-db
        image: mysql:8.2.0
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - "3306:3306"
        networks:
            - csv-import-network

    app:
        container_name: csv-import-app
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        networks:
            - csv-import-network

networks:
    csv-import-network:
        driver: bridge
